version: '3.9'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - myvol:/var/lib/docker/volumes/myvol/_data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  myvol: